### PR TITLE
MRG: Initial block methods

### PR DESCRIPTION
**Pull request by clairezurn**
Open to feedback and discussion on the block methods. Eventually I think we'll move these into a block object class. extract_unique_filename and potential_result_path could change based on our decided file structure restrictions and need unit tests.

### CODE REVIEW

**Comment by clairezurn** [comment]
I would like to remove the block_methods file from this branch before we merge. I put everything into the object class now, and I think that's the way it should stay.

**Comment by clairezurn** [comment]
Sorry, I meant to delete block_methods.py before requesting changes. Once we decided to simplify with BIDS, they all became unnecessary. 
Plan is next to write up the unit tests.

**Comment by clairezurn** [comment]
@adam2392 I can't figure out for the life of me how to get this build to find mne-bids as a module. It's the only thing stopping this from working, as far as I can tell. Pytest passes everything on my local machine. Any knowledge on how to do that? I added it to the requirements.txt file.

**Comment by clairezurn** [comment]
For the file creation/deletion, I effectively did the same thing as tempdir, but a little more bootstrap-y. I wanted to make sure I kept the folder itself intact but empty after test, and wanted four files made. From what I read, this way was as easy to do.

**Comment by adam2392** [comment]
> For the file creation/deletion, I effectively did the same thing as tempdir, but a little more bootstrap-y. I wanted to make sure I kept the folder itself intact but empty after test, and wanted four files made. From what I read, this way was as easy to do.

1. Add to README.md
2. Add the necessary package name (in conda install) to .travis.yml
3. Add to setup.py
4. Add to requirements.txt file

To verify locally, just conda/pip install mne_bids and verify import works.

**Pull request merged**
